server:
  port: 5210
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/users?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true